name: 构建 emdm-php-fpm-82 镜像
on:
  push:
    paths:
      - emdm/php-fpm/Dockerfile-php-fpm-82
      - emdm/php-fpm/entrypoint.sh
      - .github/workflows/emdm-php-fpm-82.yml
      - emdm/php-fpm/scripts/*
  schedule:
    - cron: 30 5 * * 5
  workflow_dispatch: {}
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-emdm-php-fpm-82:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 登陆到 DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 构建 emdm-php-fpm-82 镜像
        uses: docker/build-push-action@v5
        with:
          context: emdm/php-fpm
          file: emdm/php-fpm/Dockerfile-php-fpm-82
          push: true
          tags: ghcr.io/kitkat-starter/suck:php-fpm-82
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-emdm-php-fpm-82
    steps:
      - name: 检出代码
        uses: actions/checkout@v5
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images emdm/php-fpm/php-fpm-82.yml
